import numpy as np 
print("hello")
"ufiufgufgeirugiygfiygiegfiefgiegfiefgiehgfieyrfgieygfieryfgeiryfgiergfiyegfiyegri"
"""
kjhfeoihfoehfouehfoeuhfoeuherouhgeorg
oeeuhgoeuhgouhorhgoirehgorhgorugr
oruugoerughreguheorgouewrgyiughiursghsrug
houghfgoeuhgoihpeifueofuero[f
goirheguohergeiewhoewhegw
fuwegurgjhgpiwigpiirgnherg
rgheroughogpwigurhgjrgwpee
woughurghrhgiehgehrgjregwkgehgejrge
foeruhgougerjgnreihgoeuhgberjge
frgbejrgorehgebgurghbergj
bergoebverogerbgoiegwhpinrvjlnwje
foejrbvrouebvjenvpeirviernn
jebebvuerbviuebvbervbres]"""









s = 2
l = 5
u = 4
